version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 87ti5ox6
      MYSQL_DATABASE: quizzing
      MYSQL_USER:  quizzing
      MYSQL_PASSWORD: quizzing
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
  solr:
    image: solr:8.1.1
    ports:
      - "8983:8983"
  web:
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/quizzing?allowPublicKeyRetrieval=true&useSSL=false&seTimezone=true&serverTimezone=UTC
      - SPRING_DATASOLRHOST=http://solr:8983/solr
    depends_on:
      - db
volumes:
  mysql-data:
